"""Add ImageAnalysis model

Revision ID: b6313dcecc7d
Revises: d4da2d5a4e1a
Create Date: 2026-08-09 16:14:47.487981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6313dcecc7d'
down_revision: Union[str, None] = 'd4da2d5a4e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('sharpness_score', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('exposure_score', sa.Float(), nullable=True),
    sa.Column('lighting_score', sa.Float(), nullable=True),
    sa.Column('composition_score', sa.Float(), nullable=True),
    sa.Column('subject_clarity_score', sa.Float(), nullable=True),
    sa.Column('face_quality_score', sa.Float(), nullable=True),
    sa.Column('visual_appeal_score', sa.Float(), nullable=True),
    sa.Column('technical_quality_score', sa.Float(), nullable=True),
    sa.Column('is_usable', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('similarity_group', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_analysis')
    # ### end Alembic commands ###
